"""add year to raw_products

Revision ID: 07078ddd1744
Revises: bbf3f22cf5c6
Create Date: 2026-07-13 12:45:36.750016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07078ddd1744'
down_revision: Union[str, Sequence[str], None] = 'bbf3f22cf5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_products', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_products', 'year')
    # ### end Alembic commands ###
