"""fix entitlement model add primary key and org_id

Revision ID: 19f94c8f6778
Revises: 07078ddd1744
Create Date: 2026-07-14 13:23:45.686084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f94c8f6778'
down_revision: Union[str, Sequence[str], None] = '07078ddd1744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
