"""data model refactor accommodation data and aggregation sources

Revision ID: 503ec2ccebc0
Revises: 722b0f16f690
Create Date: 2026-07-30 16:49:43.884749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "503ec2ccebc0"
down_revision: Union[str, Sequence[str], None] = "722b0f16f690"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_data",
        sa.Column("external_data_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("eurostat", "ine", "scraping", "manual", name="externaldatasource"),
            nullable=False,
        ),
        sa.Column("nuts_code", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("external_data_id"),
    )
    op.create_table(
        "accommodation_data",
        sa.Column("accommodation_data_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("accommodation_id", sa.Integer(), nullable=False),
        sa.Column("raw_product_id", sa.Integer(), nullable=True),
        sa.Column("source_upload_id", sa.Integer(), nullable=True),
        sa.Column(
            "granularity",
            sa.Enum("annual", "quarterly", "monthly", name="granularitytype"),
            server_default="annual",
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("storage_path", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "state",
            sa.Enum("draft", "ready", "archived", name="accommodationdatastate"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.org_id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_product_id"], ["raw_products.product_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_upload_id"],
            ["uploads.upload_id"],
        ),
        sa.PrimaryKeyConstraint("accommodation_data_id"),
    )
    op.create_table(
        "aggregation_sources",
        sa.Column("aggregation_id", sa.Integer(), nullable=False),
        sa.Column("accommodation_data_id", sa.Integer(), nullable=True),
        sa.Column("external_data_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["accommodation_data_id"],
            ["accommodation_data.accommodation_data_id"],
        ),
        sa.ForeignKeyConstraint(
            ["aggregation_id"],
            ["aggregations.aggregation_id"],
        ),
        sa.ForeignKeyConstraint(
            ["external_data_id"],
            ["external_data.external_data_id"],
        ),
        sa.PrimaryKeyConstraint("aggregation_id"),
    )
    op.drop_table("datasets")
    op.add_column(
        "aggregations",
        sa.Column(
            "is_precomputed", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    op.add_column(
        "raw_products",
        sa.Column(
            "granularity",
            sa.Enum("annual", "quarterly", "monthly", name="granularitytype"),
            nullable=True,
            server_default="annual",
        ),
    )
    op.alter_column("raw_products", "granularity", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_products", "granularity")
    op.drop_column("aggregations", "is_precomputed")
    op.create_table(
        "datasets",
        sa.Column("dataset_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "accommodation_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("source_upload_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("granularity", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("period_start", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("period_end", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("storage_path", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "state",
            postgresql.ENUM("draft", "ready", "archived", name="datasetstate"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
            name=op.f("datasets_accommodation_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.org_id"], name=op.f("datasets_org_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["source_upload_id"],
            ["uploads.upload_id"],
            name=op.f("datasets_source_upload_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("dataset_id", name=op.f("datasets_pkey")),
    )
    op.drop_table("aggregation_sources")
    op.drop_table("accommodation_data")
    op.drop_table("external_data")
    # ### end Alembic commands ###
