"""add name field to accommodation

Revision ID: 557c86840151
Revises: 7713272aa55f
Create Date: 2026-06-20 08:02:12.130033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '557c86840151'
down_revision: Union[str, Sequence[str], None] = '7713272aa55f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodations', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint(op.f('organizations_name_key'), 'organizations', type_='unique')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'deactivated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deactivated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('organizations_name_key'), 'organizations', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('accommodations', 'name')
    # ### end Alembic commands ###
