"""initial schema

Revision ID: 5f545348cf80
Revises:
Create Date: 2026-05-13 16:12:07.706776

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f545348cf80"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aggregations",
        sa.Column("aggregation_id", sa.Integer(), nullable=False),
        sa.Column("aggregation_type", sa.String(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("storage_path", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "computing", "ready", "failed", name="aggregationstatus"
            ),
            nullable=False,
        ),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("aggregation_id"),
    )
    op.create_table(
        "organizations",
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("provider", "consumer", name="organizationtype"),
            nullable=False,
        ),
        sa.Column("points_balance", sa.Integer(), nullable=False),
        sa.Column("stripe_account_id", sa.String(), nullable=True),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("org_id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "category", sa.Enum("style", "policty", name="tagcategory"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "accommodations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "hotel", "hostel", "aparthotel", "resort", name="accommodationtype"
            ),
            nullable=False,
        ),
        sa.Column(
            "category_system",
            sa.Enum("stars", "keys", name="categorysystem"),
            nullable=True,
        ),
        sa.Column("category_value", sa.Integer(), nullable=True),
        sa.Column("current_room_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.org_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aggregated_products",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("aggregation_id", sa.Integer(), nullable=False),
        sa.Column("template_name", sa.String(), nullable=False),
        sa.Column("price_points", sa.Integer(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="aggregatedproductstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["aggregation_id"],
            ["aggregations.aggregation_id"],
        ),
        sa.PrimaryKeyConstraint("product_id"),
    )
    op.create_table(
        "uploads",
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "processing", "completed", "failed", name="upload_status"
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.org_id"],
        ),
        sa.PrimaryKeyConstraint("upload_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("org_admin", "org_member", "platform_admin", name="userrole"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.org_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "accommodation_events",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("accommodation_id", sa.Integer(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "renovation",
                "category_change",
                "capacity_change",
                "type_change",
                name="eventtype",
            ),
            nullable=False,
        ),
        sa.Column("effective_date", sa.DateTime(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "accommodation_tags",
        sa.Column("accommodation_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("accommodation_id", "tag_id"),
    )
    op.create_table(
        "data_sharing_consents",
        sa.Column("consent_id", sa.Integer(), nullable=False),
        sa.Column("accommodation_id", sa.Integer(), nullable=False),
        sa.Column("allow_raw_sharing", sa.Boolean(), nullable=False),
        sa.Column("allow_aggregated", sa.Boolean(), nullable=False),
        sa.Column(
            "revenue_share_pct", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("terms_version", sa.String(), nullable=False),
        sa.Column(
            "consent_given_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
        ),
        sa.PrimaryKeyConstraint("consent_id"),
    )
    op.create_table(
        "datasets",
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("accommodation_id", sa.Integer(), nullable=False),
        sa.Column("source_upload_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("granularity", sa.String(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("storage_path", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("draft", "ready", "archived", name="datasetstate"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.org_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_upload_id"],
            ["uploads.upload_id"],
        ),
        sa.PrimaryKeyConstraint("dataset_id"),
    )
    op.create_table(
        "market_reports",
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("aggregated_product_id", sa.Integer(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["aggregated_product_id"],
            ["aggregated_products.product_id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.org_id"],
        ),
        sa.PrimaryKeyConstraint("report_id"),
    )
    op.create_table(
        "raw_products",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("accommodation_id", sa.Integer(), nullable=False),
        sa.Column("template_name", sa.String(), nullable=False),
        sa.Column("preview_config", sa.JSON(), nullable=True),
        sa.Column("price_money", sa.Integer(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="rawproductstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
        ),
        sa.PrimaryKeyConstraint("product_id"),
    )
    op.create_table(
        "accommodation_reports",
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("raw_product_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.org_id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_product_id"],
            ["raw_products.product_id"],
        ),
        sa.PrimaryKeyConstraint("report_id"),
    )
    op.create_table(
        "capacity_changes",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("old_room_count", sa.Integer(), nullable=True),
        sa.Column("new_room_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["accommodation_events.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "category_changes",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("old_value", sa.Integer(), nullable=True),
        sa.Column("new_value", sa.Integer(), nullable=True),
        sa.Column(
            "old_system", sa.Enum("stars", "keys", name="categorysystem"), nullable=True
        ),
        sa.Column(
            "new_system", sa.Enum("stars", "keys", name="categorysystem"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["accommodation_events.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "entitlements",
        sa.Column("entitlement_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("aggregated_product_id", sa.Integer(), nullable=True),
        sa.Column("raw_product_id", sa.Integer(), nullable=True),
        sa.Column(
            "entitlement_type",
            sa.Enum("points", "purchase", "granted", name="entitlementtype"),
            nullable=False,
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["aggregated_product_id"],
            ["aggregated_products.product_id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.org_id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_product_id"],
            ["raw_products.product_id"],
        ),
        sa.PrimaryKeyConstraint("entitlement_id"),
    )
    op.create_table(
        "renovations",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column(
            "renovation_type",
            sa.Enum("partial", "full", name="renovationtype"),
            nullable=True,
        ),
        sa.Column(
            "renovation_scope",
            sa.Enum(
                "rooms",
                "common_areas",
                "amenities",
                "structural",
                "full_property",
                name="renovationscope",
            ),
            nullable=True,
        ),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["accommodation_events.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum("points_purchase", "raw_access", name="transactiontype"),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("points_awarded", sa.Integer(), nullable=True),
        sa.Column("raw_product_id", sa.Integer(), nullable=True),
        sa.Column("stripe_payment_id", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "completed", "failed", "refunded", name="transactionstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.org_id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_product_id"],
            ["raw_products.product_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_table(
        "type_changes",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column(
            "old_type",
            sa.Enum(
                "hotel", "hostel", "aparthotel", "resort", name="accommodationtype"
            ),
            nullable=True,
        ),
        sa.Column(
            "new_type",
            sa.Enum(
                "hotel", "hostel", "aparthotel", "resort", name="accommodationtype"
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["accommodation_events.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "revenue_distributions",
        sa.Column("distribution_id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("accommodation_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "revenue_share_pct", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("stripe_transfer_id", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "paid", "failed", name="revenuedistributionstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.org_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.transaction_id"],
        ),
        sa.PrimaryKeyConstraint("distribution_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("revenue_distributions")
    op.drop_table("type_changes")
    op.execute("DROP TABLE IF EXISTS transactions")
    op.drop_table("renovations")
    op.drop_table("entitlements")
    op.drop_table("category_changes")
    op.drop_table("capacity_changes")
    op.drop_table("accommodation_reports")
    op.drop_table("raw_products")
    op.drop_table("market_reports")
    op.drop_table("datasets")
    op.drop_table("data_sharing_consents")
    op.drop_table("accommodation_tags")
    op.drop_table("accommodation_events")
    op.drop_table("users")
    op.drop_table("uploads")
    op.drop_table("aggregated_products")
    op.drop_table("accommodations")
    op.drop_table("tags")
    op.drop_table("organizations")
    op.drop_table("aggregations")
    # Eliminar todos los enums
    op.execute("DROP TYPE IF EXISTS aggregationstatus")
    op.execute("DROP TYPE IF EXISTS organizationtype")
    op.execute("DROP TYPE IF EXISTS accommodationtype")
    op.execute("DROP TYPE IF EXISTS categorysystem")
    op.execute("DROP TYPE IF EXISTS eventtype")
    op.execute("DROP TYPE IF EXISTS upload_status")
    op.execute("DROP TYPE IF EXISTS datasetstate")
    op.execute("DROP TYPE IF EXISTS rawproductstatus")
    op.execute("DROP TYPE IF EXISTS aggregatedproductstatus")
    op.execute("DROP TYPE IF EXISTS entitlementtype")
    op.execute("DROP TYPE IF EXISTS revenuedistributionstatus")
    op.execute("DROP TYPE IF EXISTS paymentstatus")
    op.execute("DROP TYPE IF EXISTS pointsreason")
    op.execute("DROP TYPE IF EXISTS userrole")
    op.execute("DROP TYPE IF EXISTS tagcategory")
    op.execute("DROP TYPE IF EXISTS transactiontype")
    op.execute("DROP TYPE IF EXISTS transactionstatus")
    op.execute("DROP TYPE IF EXISTS renovationtype")
    op.execute("DROP TYPE IF EXISTS renovationscope")
    op.execute("DROP TYPE IF EXISTS invitationstatus")
