"""replace transactions with points ledger and payment records

Revision ID: 66c57a36a8a2
Revises: 5f545348cf80
Create Date: 2026-05-13 17:42:31.773797

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "66c57a36a8a2"
down_revision: Union[str, Sequence[str], None] = "5f545348cf80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_records",
        sa.Column("payment_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("points_awarded", sa.Integer(), nullable=False),
        sa.Column("stripe_payment_id", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "completed", "failed", "refunded", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.org_id"],
        ),
        sa.PrimaryKeyConstraint("payment_id"),
    )
    op.create_table(
        "points_ledger",
        sa.Column("ledger_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "purchase",
                "welcome_bonus",
                "data_used",
                "product_access",
                "refund",
                "manual",
                name="pointsreason",
            ),
            nullable=False,
        ),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("reference_type", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.org_id"],
        ),
        sa.PrimaryKeyConstraint("ledger_id"),
    )
    op.execute("DROP TABLE transactions CASCADE")
    op.add_column(
        "raw_products", sa.Column("price_points", sa.Integer(), nullable=False)
    )
    op.drop_column("raw_products", "price_money")
    op.add_column(
        "revenue_distributions",
        sa.Column("raw_product_id", sa.Integer(), nullable=False),
    )
    op.add_column(
        "revenue_distributions", sa.Column("buyer_org_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        "revenue_distributions_buyer_org_id_fkey",
        "revenue_distributions",
        "organizations",
        ["buyer_org_id"],
        ["org_id"],
    )
    op.create_foreign_key(
        "revenue_distributions_raw_product_id_fkey",
        "revenue_distributions",
        "raw_products",
        ["raw_product_id"],
        ["product_id"],
    )
    op.drop_column("revenue_distributions", "transaction_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column(
        "revenue_distributions",
        sa.Column("transaction_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "revenue_distributions_buyer_org_id_fkey",
        "revenue_distributions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "revenue_distributions_raw_product_id_fkey",
        "revenue_distributions",
        type_="foreignkey",
    )
    op.drop_column("revenue_distributions", "buyer_org_id")
    op.drop_column("revenue_distributions", "raw_product_id")
    op.add_column(
        "raw_products",
        sa.Column("price_money", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("raw_products", "price_points")
    op.drop_table("points_ledger")
    op.drop_table("payment_records")
