"""add accommodation extended data tables

Revision ID: 722b0f16f690
Revises: 4d0e421d194f
Create Date: 2026-07-29 08:52:29.126127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722b0f16f690'
down_revision: Union[str, Sequence[str], None] = '4d0e421d194f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('length_of_stay', sa.Float(), nullable=True),
    sa.Column('cpor', sa.Float(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_table('distribution_channels',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.Enum('direct_web', 'direct_phone', 'booking_com', 'expedia', 'hotels_com', 'airbnb', 'hotelbeds', 'tripadvisor', 'google_hotel', 'lastminute', 'rumbo', 'tui', 'thomas_cook', 'jet2', 'neckermann', 'kuoni', 'corendon', 'sunweb', 'loveholidays', 'on_the_beach', 'corporate', 'gds', 'wholesale', 'other_ota', 'other_tour_operator', 'other', name='channelname'), nullable=False),
    sa.Column('booking_percentage', sa.Float(), nullable=False),
    sa.Column('commission_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('revenue_breakdowns',
    sa.Column('breakdown_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('rooms', 'food_and_beverage', 'spa', 'meetings_events', 'parking', 'laundry', 'minibar', 'activities', 'other', name='revenuedepartment'), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('breakdown_id')
    )
    op.create_table('room_types',
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('single', 'double', 'twin', 'triple', 'quadruple', 'suite', 'junior_suite', 'studio', 'apartment', 'family', 'accessible', 'penthouse', 'bunk', name='roomcategory'), nullable=False),
    sa.Column('level', sa.Enum('standard', 'superior', 'deluxe', 'executive', 'luxury', 'presidential', name='roomlevel'), nullable=False),
    sa.Column('custom_name', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_type_id')
    )
    op.add_column('accommodations', sa.Column('building_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accommodations', 'building_year')
    op.drop_table('room_types')
    op.drop_table('revenue_breakdowns')
    op.drop_table('distribution_channels')
    op.drop_table('accommodation_details')
    # ### end Alembic commands ###
