"""migrate models to 2.0 sqlachemy sintaxy

Revision ID: 99c256d3e77b
Revises: 28d6ac3e94fd
Create Date: 2026-06-22 08:19:01.702275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "99c256d3e77b"
down_revision: Union[str, Sequence[str], None] = "28d6ac3e94fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accommodation_events",
        "accommodation_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "accommodation_events",
        "effective_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        nullable=False,
    )
    op.alter_column(
        "accommodation_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "accommodation_events",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "accommodation_reports",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "accommodations", "org_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "accommodations", "city", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "accommodations", "country", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "accommodations",
        "category_value",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "accommodations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "accommodations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "aggregated_products", "is_public", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "aggregated_products", "is_featured", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "aggregated_products",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "aggregated_products",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "aggregations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "capacity_changes", "old_room_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "capacity_changes", "new_room_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "category_changes", "old_value", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "category_changes", "new_value", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "category_changes",
        "old_system",
        existing_type=postgresql.ENUM("stars", "keys", name="categorysystem"),
        nullable=False,
    )
    op.alter_column(
        "category_changes",
        "new_system",
        existing_type=postgresql.ENUM("stars", "keys", name="categorysystem"),
        nullable=False,
    )
    op.alter_column(
        "data_sharing_consents",
        "consent_given_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("datasets", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "datasets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "datasets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "entitlements",
        "granted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "invitations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "market_reports",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("organizations", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "organizations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "organizations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_unique_constraint(None, "organizations", ["name"])
    op.alter_column(
        "payment_records",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "payment_records",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "points_ledger",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "raw_products", "is_public", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "raw_products", "is_featured", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "raw_products",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "raw_products",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "renovations",
        "renovation_type",
        existing_type=postgresql.ENUM("partial", "full", name="renovationtype"),
        nullable=False,
    )
    op.alter_column(
        "renovations",
        "renovation_scope",
        existing_type=postgresql.ENUM(
            "rooms",
            "common_areas",
            "amenities",
            "structural",
            "full_property",
            name="renovationscope",
        ),
        nullable=False,
    )
    op.alter_column(
        "renovations",
        "cost",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "revenue_distributions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "revenue_distributions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("tags", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "type_changes",
        "old_type",
        existing_type=postgresql.ENUM(
            "hotel", "hostel", "aparthotel", "resort", name="accommodationtype"
        ),
        nullable=False,
    )
    op.alter_column(
        "type_changes",
        "new_type",
        existing_type=postgresql.ENUM(
            "hotel", "hostel", "aparthotel", "resort", name="accommodationtype"
        ),
        nullable=False,
    )
    op.alter_column(
        "uploads",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "uploads",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "users",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "users", sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("users", "deactivated_at")
    op.drop_column("users", "is_active")
    op.alter_column(
        "uploads",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "uploads",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "type_changes",
        "new_type",
        existing_type=postgresql.ENUM(
            "hotel", "hostel", "aparthotel", "resort", name="accommodationtype"
        ),
        nullable=True,
    )
    op.alter_column(
        "type_changes",
        "old_type",
        existing_type=postgresql.ENUM(
            "hotel", "hostel", "aparthotel", "resort", name="accommodationtype"
        ),
        nullable=True,
    )
    op.alter_column("tags", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "revenue_distributions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "revenue_distributions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "renovations",
        "cost",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "renovations",
        "renovation_scope",
        existing_type=postgresql.ENUM(
            "rooms",
            "common_areas",
            "amenities",
            "structural",
            "full_property",
            name="renovationscope",
        ),
        nullable=True,
    )
    op.alter_column(
        "renovations",
        "renovation_type",
        existing_type=postgresql.ENUM("partial", "full", name="renovationtype"),
        nullable=True,
    )
    op.alter_column(
        "raw_products",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "raw_products",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "raw_products", "is_featured", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "raw_products", "is_public", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "points_ledger",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "payment_records",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "payment_records",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint("organizations_name_key", "organizations", type_="unique")
    op.alter_column(
        "organizations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "organizations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("organizations", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "market_reports",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "invitations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "entitlements",
        "granted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "datasets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "datasets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("datasets", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "data_sharing_consents",
        "consent_given_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "category_changes",
        "new_system",
        existing_type=postgresql.ENUM("stars", "keys", name="categorysystem"),
        nullable=True,
    )
    op.alter_column(
        "category_changes",
        "old_system",
        existing_type=postgresql.ENUM("stars", "keys", name="categorysystem"),
        nullable=True,
    )
    op.alter_column(
        "category_changes", "new_value", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "category_changes", "old_value", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "capacity_changes", "new_room_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "capacity_changes", "old_room_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "aggregations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "aggregated_products",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "aggregated_products",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "aggregated_products", "is_featured", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "aggregated_products", "is_public", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "accommodations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "accommodations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "accommodations",
        "category_value",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "accommodations", "country", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("accommodations", "city", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "accommodations", "org_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "accommodation_reports",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "accommodation_events",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "accommodation_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "accommodation_events",
        "effective_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "accommodation_events",
        "accommodation_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
