"""replace city and country with location json in accommodations

Revision ID: bbf3f22cf5c6
Revises: debcb3c7a60d
Create Date: 2026-07-09 09:54:32.258448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf3f22cf5c6'
down_revision: Union[str, Sequence[str], None] = 'debcb3c7a60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodations', sa.Column('location', sa.JSON(), nullable=True))
    op.drop_column('accommodations', 'city')
    op.drop_column('accommodations', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodations', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('accommodations', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('accommodations', 'location')
    # ### end Alembic commands ###
