"""replace status with is_active in products and add aggregated product status

Revision ID: d6f771f17e43
Revises: f6ec6e078c00
Create Date: 2026-07-08 10:09:19.068008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6f771f17e43'
down_revision: Union[str, Sequence[str], None] = 'f6ec6e078c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creation_events')
    op.add_column('aggregated_products', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('raw_products', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.drop_column('raw_products', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_products', sa.Column('status', postgresql.ENUM('active', 'inactive', name='rawproductstatus'), autoincrement=False, nullable=False))
    op.drop_column('raw_products', 'is_active')
    op.drop_column('aggregated_products', 'is_active')
    op.create_table('creation_events',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('initial_type', postgresql.ENUM('hotel', 'hostel', 'aparthotel', 'resort', name='accommodationtype'), autoincrement=False, nullable=False),
    sa.Column('initial_category_system', postgresql.ENUM('stars', 'keys', name='categorysystem'), autoincrement=False, nullable=False),
    sa.Column('initial_category_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('initial_room_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['accommodation_events.event_id'], name=op.f('creation_events_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('creation_events_pkey'))
    )
    # ### end Alembic commands ###
