"""add ownership structure to accommodations

Revision ID: d96fbe718959
Revises: e5d2b77850da
Create Date: 2026-08-13 11:49:31.674614

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d96fbe718959"
down_revision: Union[str, Sequence[str], None] = "e5d2b77850da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ownership_structure_enum = sa.Enum(
        "direct_ownership",
        "management_contract",
        "franchise",
        "manchise",
        "lease",
        "timeshare",
        "condo_hotel",
        name="ownershipstructure",
    )
    ownership_structure_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "accommodations",
        sa.Column(
            "ownership_structure",
            sa.Enum(
                "direct_ownership",
                "management_contract",
                "franchise",
                "manchise",
                "lease",
                "timeshare",
                "condo_hotel",
                name="ownershipstructure",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accommodations", "ownership_structure")
    # ### end Alembic commands ###
