"""add is_active to entitlements

Revision ID: debcb3c7a60d
Revises: d6f771f17e43
Create Date: 2026-07-08 10:36:24.152625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'debcb3c7a60d'
down_revision: Union[str, Sequence[str], None] = 'd6f771f17e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entitlements', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entitlements', 'is_active')
    # ### end Alembic commands ###
