"""remove tags add accommodation themes and certifications

Revision ID: e5d2b77850da
Revises: 503ec2ccebc0
Create Date: 2026-08-12 15:28:14.767802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e5d2b77850da"
down_revision: Union[str, Sequence[str], None] = "503ec2ccebc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accommodation_certifications",
        sa.Column("certification_id", sa.Integer(), nullable=False),
        sa.Column("accommodation_id", sa.Integer(), nullable=False),
        sa.Column(
            "certification_type",
            sa.Enum(
                "iso_14001",
                "iso_9001",
                "travelife",
                "green_key",
                "blue_flag",
                "q_calidad_turistica",
                "breeam",
                "leed",
                "other",
                name="certificationtype",
            ),
            nullable=False,
        ),
        sa.Column("custom_name", sa.String(), nullable=True),
        sa.Column("obtained_year", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["accommodation_id"], ["accommodations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("certification_id"),
    )
    op.create_table(
        "accommodation_themes",
        sa.Column("theme_id", sa.Integer(), nullable=False),
        sa.Column("accommodation_id", sa.Integer(), nullable=False),
        sa.Column(
            "theme_type",
            sa.Enum(
                "boutique",
                "spa_wellness",
                "themed",
                "eco_sustainable",
                "bed_and_breakfast",
                "beach",
                "luxury",
                "historic_building",
                "business",
                "family",
                "design",
                "golf",
                "rural",
                "urban",
                "all_inclusive",
                "extended_stay",
                "airport",
                "other",
                name="themetype",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accommodation_id"], ["accommodations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("theme_id"),
    )
    op.drop_table("accommodation_tags")
    op.drop_table("tags")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accommodation_tags",
        sa.Column(
            "accommodation_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
            name=op.f("accommodation_tags_accommodation_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("accommodation_tags_tag_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "accommodation_id", "tag_id", name=op.f("accommodation_tags_pkey")
        ),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM("style", "policty", name="tagcategory"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tags_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("tags_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("accommodation_themes")
    op.drop_table("accommodation_certifications")
    # ### end Alembic commands ###
